src/Opdex.Platform.WebApi/Exceptions/TooManyRequestsException.cs, src/Opdex.Platform.WebApi/Opdex.Platform.WebApi.csproj, src/Opdex.Platform.WebApi/Startup.cs, src/Opdex.Platform.WebApi/appsettings.json
Basic IP rate limiting. Allows us to configure rules for each API instance.
Config can be used to turn off rate limiting for specific IP ranges, which could be useful, for example, if you wanted to route traffic through an API gateway.
=> [PAPI-170] IP rate limiting

src/Opdex.Platform.Application.Abstractions/EntryQueries/LiquidityPools/Snapshots/GetLiquidityPoolSnapshotsWithFilterQuery.cs, src/Opdex.Platform.Application.Abstractions/Models/LiquidityPools/LiquidityPoolSnapshotDto.cs, src/Opdex.Platform.Application.Abstractions/Models/LiquidityPools/LiquidityPoolSnapshotsDto.cs, src/Opdex.Platform.Application.Abstractions/Queries/LiquidityPools/Snapshots/RetrieveLiquidityPoolSnapshotsWithFilterQuery.cs, src/Opdex.Platform.Application/Assemblers/LiquidityPoolDtoAssembler.cs, src/Opdex.Platform.Application/EntryHandlers/LiquidityPools/Snapshots/CreateRewindLiquidityPoolDailySnapshotCommandHandler.cs, src/Opdex.Platform.Application/EntryHandlers/LiquidityPools/Snapshots/GetLiquidityPoolSnapshotsWithFilterQueryHandler.cs, src/Opdex.Platform.Application/EntryHandlers/Tokens/Snapshots/CreateRewindTokenDailySnapshotCommandHandler.cs, src/Opdex.Platform.Application/Handlers/LiquidityPools/Snapshots/RetrieveLiquidityPoolSnapshotsWithFilterQueryHandler.cs, src/Opdex.Platform.Application/PlatformApplicationMapperProfile.cs, src/Opdex.Platform.Application/PlatformApplicationServiceCollectionExtensions.cs, src/Opdex.Platform.Infrastructure.Abstractions/Data/Queries/LiquidityPools/Snapshots/SelectLiquidityPoolSnapshotsWithFilterQuery.cs, src/Opdex.Platform.Infrastructure.Abstractions/Data/Queries/Tokens/Snapshots/SelectTokenSnapshotsWithFilterQuery.cs, src/Opdex.Platform.Infrastructure/Data/Handlers/LiquidityPools/Snapshots/SelectLiquidityPoolSnapshotsWithFilterQueryHandler.cs, src/Opdex.Platform.Infrastructure/Data/Handlers/Tokens/Snapshots/SelectTokenSnapshotsWithFilterQueryHandler.cs, src/Opdex.Platform.Infrastructure/PlatformInfrastructureMapperProfile.cs, src/Opdex.Platform.WebApi/Controllers/LiquidityPoolsController.cs, src/Opdex.Platform.WebApi/Mappers/PlatformWebApiMapperProfile.cs, src/Opdex.Platform.WebApi/Models/Requests/LiquidityPools/LiquidityPoolFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/SnapshotFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Tokens/TokenFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Responses/Pools/LiquidityPoolSnapshotResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Pools/LiquidityPoolSnapshotsResponseModel.cs, test/Opdex.Platform.Application.Abstractions.Tests/EntryQueries/LiquidityPools/Snapshots/GetLiquidityPoolSnapshotsWithFilterQueryTests.cs, test/Opdex.Platform.Application.Abstractions.Tests/EntryQueries/MarketTokens/Snapshots/GetMarketTokenSnapshotsWithFilterQueryTests.cs, test/Opdex.Platform.Application.Tests/EntryHandlers/LiquidityPools/Snapshots/GetLiquidityPoolSnapshotsWithFilterQueryHandlerTests.cs, test/Opdex.Platform.Application.Tests/EntryHandlers/Tokens/Snapshots/GetTokenSnapshotsWithFilterQueryHandlerTests.cs, test/Opdex.Platform.Infrastructure.Tests/Data/Handlers/LiquidityPools/Snapshots/SelectLiquidityPoolSnapshotsWithFilterQueryHandlerTests.cs, test/Opdex.Platform.WebApi.Tests/Controllers/LiquidityPoolsControllerTests/GetLiquidityPoolHistoryTests.cs
Implements pagination on the get liquidity pool history endpoint following the get token history implementation.
*adding more test coverage but otherwise ready for review*
=> [PAPI-88] Liquidity Pool History

src/Opdex.Platform.WebApi/IndexerBackgroundService.cs, test/Opdex.Platform.WebApi.Tests/IndexerBackgroundServiceTests.cs
Attempt at resolving the occasional indexer locking seen on Testnet.
If the indexer is locked and the indexer comes back around to process next blocks, check if the instance that locked the table is the instance attempting to index, if so, unlock and move forward.
Based on findings of this implementation, we can take it further with a rewind to ensure no data was missed.
=> Attempt Indexer Unlock

src/Opdex.Platform.Domain/Models/Transactions/SmartContractMethodParameter.cs, src/Opdex.Platform.WebApi/Controllers/DeployController.cs, test/Opdex.Platform.Domain.Tests/Models/Transactions/SmartContractMethodParameterTests.cs
* Correctly (de)serialize byte array smart contract params
* Remove auth from deployment - you can only have a market address of the auth token once the contracts are deployed
=> [PAPI-247] Deploy Fixes

.vscode/launch.json, .vscode/tasks.json, src/Opdex.Platform.Infrastructure.Abstractions/Data/Queries/Addresses/Balances/AddressBalancesCursor.cs, src/Opdex.Platform.Infrastructure/Data/Handlers/Addresses/Balances/SelectAddressBalancesWithFilterQueryHandler.cs, src/Opdex.Platform.WebApi/Models/Requests/Wallets/AddressBalanceFilterParameters.cs, test/Opdex.Platform.Application.Tests/EntryHandlers/Addresses/Balances/GetAddressBalancesWithFilterQueryHandlerTests.cs, test/Opdex.Platform.Infrastructure.Abstractions.Tests/Data/Queries/Addresses/AddressBalancesCursorTests.cs, test/Opdex.Platform.Infrastructure.Tests/Data/Handlers/Addresses/Balances/SelectAddressBalancesWithFilterQueryHandlerTests.cs, test/Opdex.Platform.WebApi.Tests/Models/Requests/Wallets/AddressBalanceFilterParametersTests.cs
Replaces `IncludeLpTokens` filter with `TokenType` that allows balances to be filtered by: `NonProvisional`, `Provisional` and `All`.
=> [PAPI-244] Wallet position improvements

src/Opdex.Platform.WebApi/Models/Requests/FilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Governances/GovernanceFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/LiquidityPools/LiquidityPoolFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Markets/MarketSnapshotFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/MiningPools/MiningPoolFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/SnapshotFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Tokens/TokenFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Transactions/TransactionFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Vaults/VaultCertificateFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Vaults/VaultFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Wallets/AddressBalanceFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Wallets/MiningPositionFilterParameters.cs, src/Opdex.Platform.WebApi/Models/Requests/Wallets/StakingPositionFilterParameters.cs, src/Opdex.Platform.WebApi/Startup.cs, src/Opdex.Platform.WebApi/Validation/AbstractCursorValidator.cs, src/Opdex.Platform.WebApi/Validation/SnapshotFilterParametersValidator.cs, src/Opdex.Platform.WebApi/Validation/Tokens/TokenFilterParametersValidator.cs, test/Opdex.Platform.WebApi.Tests/Models/Requests/MiningPools/MiningPoolFilterParametersTests.cs, test/Opdex.Platform.WebApi.Tests/Models/Requests/Transactions/TransactionFilterParametersTests.cs, test/Opdex.Platform.WebApi.Tests/Models/Requests/Vaults/VaultCertificateFilterParametersTests.cs, test/Opdex.Platform.WebApi.Tests/Models/Requests/Vaults/VaultFilterParametersTests.cs, test/Opdex.Platform.WebApi.Tests/Models/Requests/Wallets/AddressBalanceFilterParametersTests.cs, test/Opdex.Platform.WebApi.Tests/Models/Requests/Wallets/MiningPositionFilterParametersTests.cs, test/Opdex.Platform.WebApi.Tests/Models/Requests/Wallets/StakingPositionFilterParametersTests.cs, test/Opdex.Platform.WebApi.Tests/Validation/AbstractCursorValidatorTests.cs, test/Opdex.Platform.WebApi.Tests/Validation/Tokens/TokenFilterParametersValidatorTests.cs
* Adds minimum/maximum to integer query params
* Cleans up nullable usage
* Mark required query params
* Renamed Provisional query param to TokenType to be consistent
Fairly ugly using attributes, although unfortunately it's not an easy feat to do it any other way. Also limited to what we can define. For example, we cannot really define regex patterns for addresses, as attributes are setup with constant values and the address format would have to be resolved based on the network config.
Only concern is NSwag generates minimum/maximum with a decimal point, so `1.0` as an example. _Shouldn't_ be a problem as it's defined integer but something to watch out for.
=> [PAPI-231] Query params schema

src/Opdex.Platform.WebApi/Models/Requests/Index/RewindRequest.cs, src/Opdex.Platform.WebApi/Models/Requests/Markets/CreateStandardMarketQuoteRequest.cs, src/Opdex.Platform.WebApi/Models/Requests/WalletTransactions/AddLiquidityRequest.cs, src/Opdex.Platform.WebApi/Models/Responses/Blocks/BlockResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Governances/MiningGovernanceResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/MiningPools/MiningPoolResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/OHLC/OhlcDecimalResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Pools/LiquidityPoolResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Pools/LiquidityPoolSummaryResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Pools/ReservesResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Pools/RewardsResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Pools/StakingResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Pools/VolumeResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Tokens/TokenResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Tokens/TokenSummaryResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Transactions/TransactionQuoteResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Transactions/TransactionResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Vaults/VaultCertificateResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Vaults/VaultResponseModel.cs
Specifies minimum and maximum on number fields for OpenAPI. Use of `double.MaxValue` indicates NSwag to ignore the maximum. Pretty ugly but it's the only way.
=> [PAPI-149] Minimum and maximum

src/Opdex.Platform.WebApi/Controllers/WalletsController.cs, src/Opdex.Platform.WebApi/OpenApi/Wallets/GetAddressBalanceByTokenOperationProcessor.cs, src/Opdex.Platform.WebApi/OpenApi/Wallets/RefreshAddressBalanceOperationProcessor.cs
* Amends OpenAPI definition so CRS is valid parameter for token parameter on `GET/POST /wallet/{address}/balance/{token}`.
* Force returning 401 if CRS is provided to `GET /wallet/{address}/allowance/{token}/spender/{spender}`, otherwise it returns 500 (call to full node fails)
=> [PAPI-307] Token validation improvements

docs/openapi.yml, src/Opdex.Platform.Application.Abstractions/EntryCommands/Transactions/CreateNotifyUserOfTransactionBroadcastCommand.cs, src/Opdex.Platform.Application/EntryHandlers/Transactions/CreateNotifyUserOfTransactionBroadcastCommandHandler.cs, src/Opdex.Platform.Application/Handlers/Transactions/RetrieveCirrusUnverifiedTransactionSenderByHashQueryHandler.cs, src/Opdex.Platform.Infrastructure.Abstractions/Clients/CirrusFullNodeApi/Models/RawTransactionDto.cs, src/Opdex.Platform.Infrastructure.Abstractions/Clients/CirrusFullNodeApi/Queries/Transactions/CallCirrusGetRawTransactionQuery.cs, src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/Handlers/Transactions/CallCirrusGetRawTransactionQueryHandler.cs, src/Opdex.Platform.WebApi/Controllers/TransactionsController.cs, src/Opdex.Platform.WebApi/Models/Requests/Transactions/TransactionBroadcastNotificationRequest.cs, src/Opdex.Platform.WebApi/Validation/Transactions/TransactionBroadcastNotificationValidator.cs, test/Opdex.Platform.Application.Tests/EntryHandlers/Transactions/CreateNotifyUserOfTransactionBroadcastCommandHandlerTests.cs, test/Opdex.Platform.Application.Tests/Handlers/Transactions/RetrieveCirrusUnverifiedTransactionSenderByHashQueryHandlerTests.cs, test/Opdex.Platform.WebApi.Tests/Validation/Transactions/TransactionBroadcastNotificationValidatorTests.cs
- Checks for raw transaction change address
- Attempt to find raw transaction, 5 retries, 3 seconds in between, not found after retries throws `NotFoundException`
- If change address is found, validates the requests public key matches change address
- On success, notify
- On failure, don't notify
- If change address is not found, uses the requests public key for notification
Ultimately a shorter term fix until we work into deserializing the raw transaction in API or via FN, to notify the _actual_ transaction sender.
=> [PAPI-331] Notify Broadcasted Transaction Improvements

docs/openapi.yml, src/Opdex.Platform.Infrastructure/Clients/SignalR/PlatformHub.cs, src/Opdex.Platform.WebApi/Controllers/AuthController.cs, test/Opdex.Platform.WebApi.Tests/Controllers/AuthControllerTests.cs
- Adds **GET** `/auth` endpoint to get a new StratisId to sign
- Migrated **POST** `/auth` to **POST** `/auth/callback` for default SSAS flows with sockets
- Adjusts **POST** `/auth` to validate signatures and return JWT directly
---
The additional endpoints provide a way for API based clients to authenticate themselves rather than their users such as within Postman, or a bot based API for example for retrieving transaction quotes and acting upon the results.
Naming probably could be better, the new auth routes could add `Direct` to the naming and the socket based flows `Socket` or `Callback` etc. or leave as is. More of a nit, but could clarify the differences more for clients.
=> [PAPI-292] Additional Auth Methods

docs/openapi.js, docs/openapi.yml, src/Opdex.Platform.WebApi/Startup.cs
Inject swagger config within a JS file allowing for dynamic server urls when running the project vs static server urls within `openapi.yml`.
Now swagger environments will load correctly and openapi.yml imports default to testnet
=> [PAPI-336] Inject Swagger Configi

src/Opdex.Platform.WebApi/Startup.cs
Fixes bug where cached responses were being returned despite query params being changed
=> [PAPI] Vary cache response on all query params

docs/openapi.yml, src/Opdex.Platform.Application.Abstractions/Models/LiquidityPools/LiquidityPoolDto.cs, src/Opdex.Platform.Application.Abstractions/Models/LiquidityPools/StakingDto.cs, src/Opdex.Platform.Application.Abstractions/Models/Markets/MarketDto.cs, src/Opdex.Platform.Application/Assemblers/LiquidityPoolDtoAssembler.cs, src/Opdex.Platform.Application/Assemblers/MarketDtoAssembler.cs, src/Opdex.Platform.WebApi/Mappers/PlatformWebApiMapperProfile.cs, src/Opdex.Platform.WebApi/Models/Responses/LiquidityPools/LiquidityPoolTokenGroupResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/LiquidityPools/Summary/StakingResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Markets/MarketResponseModel.cs, src/Opdex.Platform.WebApi/Models/Responses/Markets/MarketTokenGroupResponseModel.cs, test/Opdex.Platform.Application.Tests/EntryHandlers/Markets/GetMarketsWithFilterQueryHandlerTests.cs
Cleans up the market and liquidity pool responses so that they are structured in the same way. Makes it easier to consume data and store only what is cared for.
Also includes a fix so that no staking summary is returned for standard markets.
=> [PAPI-354] Market and liquidity pool response cleanup

src/Opdex.Platform.WebApi/Mappers/TransactionErrors.cs
Maps the distribution error message correctly, avoiding `Unexpected error`
=> [PAPI-380] Fix mined token error mapping

src/Opdex.Platform.Application.Abstractions/Queries/Transactions/RetrieveCirrusTransactionByHashQuery.cs, src/Opdex.Platform.Application/EntryHandlers/Transactions/CreateTransactionCommandHandler.cs, src/Opdex.Platform.Application/EntryHandlers/Transactions/ProcessCoreDeploymentTransactionCommandHandler.cs, src/Opdex.Platform.Application/Handlers/Transactions/RetrieveCirrusTransactionByHashQueryHandler.cs, src/Opdex.Platform.Application/Opdex.Platform.Application.csproj, src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/Modules/BlockStoreModule.cs, src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/Modules/NodeModule.cs, src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/Modules/SmartContractsModule.cs, src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/Modules/WalletModule.cs, src/Opdex.Platform.Infrastructure/Clients/CoinMarketCapApi/Modules/QuotesModule.cs, src/Opdex.Platform.Infrastructure/Http/ApiClientBase.cs
* Resiliency improvements to retry retrieval of transactions from Cirrus
* Update module classes to not elide async/await (following [these recommendations](https://blog.stephencleary.com/2016/12/eliding-async-await.html))
=> [PAPI-383] Retrieve transaction from Cirrus retries

src/Opdex.Platform.Application/Assemblers/VaultCertificateDtoAssembler.cs, src/Opdex.Platform.Application/Opdex.Platform.Application.csproj, src/Opdex.Platform.Application/PlatformApplicationMapperProfile.cs, src/Opdex.Platform.Infrastructure/Opdex.Platform.Infrastructure.csproj, src/Opdex.Platform.Infrastructure/PlatformInfrastructureMapperProfile.cs, src/Opdex.Platform.WebApi/Mappers/PlatformWebApiMapperProfile.cs, src/Opdex.Platform.WebApi/Opdex.Platform.WebApi.csproj, test/Opdex.Platform.Application.Tests/Mappers/AddressesPlatformApplicationMapperProfileTests.cs, test/Opdex.Platform.Infrastructure.Tests/SignalRTests/PlatformHubTests.cs
AutoMapper v11 has breaking changes. See [upgrade guide](https://docs.automapper.org/en/latest/11.0-Upgrade-Guide.html#forallothermembers-was-removed). It is currently the only dependency that we have with breaking changes.
We can no longer use `ForAllOtherMembers`, so instead I've opted to replace this with `ValidateMemberList(MemberList.None)`, to keep the behaviour where unspecified properties do not cause a runtime exception.
Going forward, I believe it will be best to aim to explicitly ignore unmapped properties. This is required for properties where we have two properties of the same name, but with different types (for example, where we have an assembler, the mapping fails for Amount -> FixedDecimal and must be ignored).
=> [PAPI-387] Upgrade AutoMapper to v11

src/Opdex.Platform.WebApi/Exceptions/MaintenanceLockException.cs, src/Opdex.Platform.WebApi/MaintenanceConfiguration.cs, src/Opdex.Platform.WebApi/Middleware/MaintenanceLockMiddleware.cs, src/Opdex.Platform.WebApi/Startup.cs, src/Opdex.Platform.WebApi/appsettings.json, test/Opdex.Platform.WebApi.Tests/Middleware/MaintenanceLockMiddlewareTests.cs
Adds the ability to make the API unavailable through configuration, for precautionary measure
=> [PAPI-390] Maintenance lock 

src/Opdex.Platform.WebApi/Validation/AbstractCursorValidator.cs
Removes validation for filter being provided alongside cursors. This makes it easier for certain clients to make paginated requests
=> [PAPI-348] Allow cursor alongside filters

docs/openapi.yml, src/Opdex.Platform.Application.Abstractions/Models/Markets/MarketSummaryDto.cs, src/Opdex.Platform.Application/Handlers/LiquidityPools/MakeLiquidityPoolCommandHandler.cs, src/Opdex.Platform.Application/PlatformApplicationMapperProfile.cs, src/Opdex.Platform.Domain/Models/Markets/MarketSummary.cs, src/Opdex.Platform.Infrastructure.Abstractions/Data/Commands/Markets/ExecuteUpdateMarketSummaryLiquidityPoolCountCommand.cs, src/Opdex.Platform.Infrastructure.Abstractions/Data/Models/Markets/MarketSummaryEntity.cs, src/Opdex.Platform.Infrastructure/Data/Handlers/Markets/Summaries/ExecuteUpdateMarketSummaryLiquidityPoolCountCommandHandler.cs, src/Opdex.Platform.Infrastructure/Data/Handlers/Markets/Summaries/SelectMarketSummaryByMarketIdQueryHandler.cs, src/Opdex.Platform.Infrastructure/PlatformInfrastructureMapperProfile.cs, src/Opdex.Platform.Infrastructure/PlatformInfrastructureServiceCollectionExtensions.cs, src/Opdex.Platform.WebApi/Mappers/PlatformWebApiMapperProfile.cs, src/Opdex.Platform.WebApi/Models/Responses/Markets/MarketSummaryResponseModel.cs, test/Opdex.Platform.Application.Tests/Handlers/LiquidityPools/MakeLiquidityPoolCommandHandlerTests.cs, test/Opdex.Platform.Domain.Tests/Models/Markets/MarketSummaryTests.cs, test/Opdex.Platform.Infrastructure.Tests/Data/Handlers/Markets/Summaries/ExecuteUpdateMarketSummaryLiquidityPoolCountCommandHandlerTests.cs, test/Opdex.Platform.Infrastructure.Tests/Data/Handlers/Markets/Summaries/PersistMarketSummaryCommandHandlerTests.cs
Returns the count of liquidity pools in a market as part of the market summary.
Depends on https://github.com/Opdex/opdex-v1-db/pull/41
=> [PAPI-394] Market liquidity pool count

src/Opdex.Platform.Application/EntryHandlers/Tokens/CreateTokenCommandHandler.cs, src/Opdex.Platform.Application/EntryHandlers/Transactions/ProcessGovernanceDeploymentTransactionCommandHandler.cs, src/Opdex.Platform.Application/EntryHandlers/Transactions/TransactionLogs/MarketDeployers/ProcessCreateMarketLogCommandHandler.cs
When a pool was created, most of the time, we'd already know about the token through our validation process. 
When creating the pool and attempting to persist the SRC token, if it already exists, try to persist additional attributes rather than returning out early.
`MakeTokenAttributeCommand` will only attempt to persist attributes that are not already applied to the given token. 
Hide whitespace for easier review.
=> [PAPI-397] Persist Attributes

src/Opdex.Platform.WebApi/Program.cs
The long reload interval makes it difficult to diagnose key vault caching issues. Reducing it won't be a problem because it doesn't consume a lot of resources and won't even get close to any Azure limits. Every 16 seconds matches with block time, so config changes _should_ get propagated for the following block.
=> [PAPI-399] Reduce AKV reload interval

src/Opdex.Platform.Common/Extensions/MathExtensions.cs, test/Opdex.Platform.Common.Tests/Extensions/MathExtensionsTests.cs
Resolves a bug where staking rewards are persisted correctly but returning incorrectly for ODX liquidity pools.
=> [PAPI-420] Staking Reward Calc Fix

src/Opdex.Platform.Infrastructure.Abstractions/Clients/CirrusFullNodeApi/Models/LocalCallResponseDto.cs, src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/Modules/SmartContractsModule.cs
Retries local calls when there's a "No code at this address." response from the node. Uses an backoff of 500ms -> 1s -> 1.5s
=> [PAPI-421] Local call retries

src/Opdex.Platform.Domain/Models/Transactions/Transaction.cs
Fixes issues retrieving transactions where the execution ran out of gas, or the call was invalid. For example, processing the following receipt:
```json
{
"transactionHash": "ad5df977f416e28264e9eff94794eccb1442d58a8a21478268f95e5b67f6168c",
"blockHash": "19dcdb7f2c289675ede3a9bbd40ae3c68d8aa33b98f8d3493a49e3f83d272437",
"blockNumber": 3427148,
"postState": "f2ae9aaeafd85eddb25f9512d59cc4bf6bba3a391510cda135a0efb9b1fad8a6",
"gasUsed": 12000,
"from": "tLvZdzinedNTM8QCFR5XaQdcSUaQXn7HSm",
"to": null,
"newContractAddress": null,
"success": false,
"returnValue": null,
"bloom": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> Allow for null 'to' address when trx failed
