src/Opdex.Platform.WebApi/IndexerBackgroundService.cs

* Dispose service collection scope early
* Apply logging scope of indexer to all indexer logs
* Try finally around process latest blocks for extra certainty

Indexer Unlock Amendments

---

src/Opdex.Platform.Application.Abstractions/EntryCommands/Addresses/Balances/CreateRefreshAddressBalanceCommand.cs
src/Opdex.Platform.Application/EntryHandlers/Addresses/Balances/CreateRefreshAddressBalanceCommandHandler.cs
src/Opdex.Platform.Application/Handlers/Addresses/Balances/RetrieveAddressBalanceByOwnerAndTokenQueryHandler.cs
src/Opdex.Platform.Application/PlatformApplicationServiceCollectionExtensions.cs
src/Opdex.Platform.Infrastructure.Abstractions/Clients/CirrusFullNodeApi/Queries/Balances/CallCirrusGetAddressCrsBalanceQuery.cs
src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/Handlers/Balances/CallCirrusGetAddressCrsBalanceQueryHandler.cs
src/Opdex.Platform.Infrastructure/PlatformInfrastructureServiceCollectionExtensions.cs
src/Opdex.Platform.WebApi/Controllers/WalletsController.cs
src/Opdex.Platform.WebApi/Models/Requests/Wallets/AddressBalanceFilterParameters.cs
src/Opdex.Platform.WebApi/Models/Requests/Wallets/MiningPositionFilterParameters.cs
src/Opdex.Platform.WebApi/Models/Requests/Wallets/StakingPositionFilterParameters.cs
src/Opdex.Platform.WebApi/Models/Responses/Status/StatusResponseModel.cs
src/Opdex.Platform.WebApi/Models/Responses/Wallet/AddressBalanceResponseModel.cs
src/Opdex.Platform.WebApi/Models/Responses/Wallet/AddressBalancesResponseModel.cs
src/Opdex.Platform.WebApi/Models/Responses/Wallet/ApprovedAllowanceResponseModel.cs
src/Opdex.Platform.WebApi/Models/Responses/Wallet/MiningPositionResponseModel.cs
src/Opdex.Platform.WebApi/Models/Responses/Wallet/MiningPositionsResponseModel.cs
src/Opdex.Platform.WebApi/Models/Responses/Wallet/StakingPositionResponseModel.cs
src/Opdex.Platform.WebApi/Models/Responses/Wallet/StakingPositionsResponseModel.cs
test/Opdex.Platform.Application.Tests/Handlers/Addresses/Balances/CreateRefreshAddressBalanceCommandHandlerTests.cs
test/Opdex.Platform.Application.Tests/Handlers/Addresses/Balances/RetrieveAddressBalanceByOwnerAndTokenQueryHandlerTests.cs
test/Opdex.Platform.Infrastructure.Tests/CirrusFullNodeApiTests/Handlers/Balances/CallCirrusGetAddressCrsBalanceQueryHandlerTests.cs
test/Opdex.Platform.WebApi.Tests/Controllers/WalletsControllerTests.cs

* Adds an endpoint to pull and index latest wallet balance for a token
* Added wallet endpoint OpenAPI examples

[PAPI-251][PAPI-254] Refresh wallet balances

---

src/Opdex.Platform.Application.Abstractions/EntryQueries/Blocks/GetLatestBlockQuery.cs
src/Opdex.Platform.Application/EntryHandlers/Blocks/GetLatestBlockQueryHandler.cs
src/Opdex.Platform.Application/PlatformApplicationServiceCollectionExtensions.cs
src/Opdex.Platform.Common/Exceptions/AlreadyIndexedException.cs
src/Opdex.Platform.Common/Exceptions/InvalidDataException.cs
src/Opdex.Platform.WebApi/Controllers/DeployController.cs
src/Opdex.Platform.WebApi/Controllers/IndexController.cs
src/Opdex.Platform.WebApi/Models/Requests/Index/ResyncFromDeploymentRequest.cs
src/Opdex.Platform.WebApi/Models/Requests/Index/RewindRequest.cs
src/Opdex.Platform.WebApi/Models/Responses/Blocks/BlockResponseModel.cs
src/Opdex.Platform.WebApi/Startup.cs
test/Opdex.Platform.Application.Tests/EntryHandlers/Blocks/GetLatestBlockQueryHandlerTests.cs
test/Opdex.Platform.WebApi.Tests/Controllers/IndexControllerTests/LastSyncedBlockTests.cs
test/Opdex.Platform.WebApi.Tests/Controllers/IndexControllerTests/RewindTests.cs

* OpenAPI examples
* Completed TODO for `GET /index/latest-block`

[PAPI-238] Indexer OpenAPI examples

---

src/Opdex.Platform.Infrastructure/Data/Handlers/Blocks/ExecuteRewindToBlockCommandHandler.cs
src/Opdex.Platform.WebApi/Startup.cs

Intends to reduce the amount of bloat in structured logs.

[OPS-18] Clear up rewind exceptions

---

src/Opdex.Platform.Application.Abstractions/Commands/Indexer/MakeIndexerLockCommand.cs
src/Opdex.Platform.Application/EntryHandlers/Blocks/CreateRewindToBlockCommandHandler.cs
src/Opdex.Platform.Application/Handlers/Indexer/MakeIndexerLockCommandHandler.cs
src/Opdex.Platform.Application/Handlers/Indexer/MakeIndexerUnlockCommandHandler.cs
src/Opdex.Platform.Domain/Models/IndexLock.cs
src/Opdex.Platform.Infrastructure.Abstractions/Data/Commands/Indexer/PersistIndexerLockCommand.cs
src/Opdex.Platform.Infrastructure.Abstractions/Data/Models/IndexLockEntity.cs
src/Opdex.Platform.Infrastructure/Data/Handlers/Indexer/PersistIndexerLockCommandHandler.cs
src/Opdex.Platform.Infrastructure/Data/Handlers/Indexer/PersistIndexerUnlockCommandHandler.cs
src/Opdex.Platform.Infrastructure/Data/Handlers/Indexer/SelectIndexerLockQueryHandler.cs
src/Opdex.Platform.WebApi/Controllers/DeployController.cs
src/Opdex.Platform.WebApi/Controllers/IndexController.cs
src/Opdex.Platform.WebApi/IndexerBackgroundService.cs
test/Opdex.Platform.Application.Tests/EntryHandlers/Blocks/CreateRewindToBlockCommandHandlerTests.cs
test/Opdex.Platform.Application.Tests/Handlers/Indexer/MakeIndexerLockCommandHandlerTests.cs
test/Opdex.Platform.Application.Tests/Handlers/Indexer/MakeIndexerUnlockCommandHandlerTests.cs
test/Opdex.Platform.Infrastructure.Tests/Data/Handlers/Indexer/PersistIndexerLockCommandHandlerTests.cs
test/Opdex.Platform.WebApi.Tests/IndexerBackgroundServiceTests.cs
test/Opdex.Platform.WebApi.Tests/Validation/LiquidityPools/LiquidityPoolFilterParametersValidatorTests.cs
test/Opdex.Platform.WebApi.Tests/Validation/Tokens/TokenFilterParametersValidatorTests.cs

* Adds Reason column to index lock
* Checks Reason is Index before attempting to force unlock if same instance has come around

[PAPI-266] Index lock reason

---

src/Opdex.Platform.Infrastructure/Clients/SignalR/PlatformHub.cs
src/Opdex.Platform.Infrastructure/Opdex.Platform.Infrastructure.csproj
src/Opdex.Platform.WebApi/Auth/WalletAddressUserIdProvider.cs
src/Opdex.Platform.WebApi/Controllers/AuthController.cs
src/Opdex.Platform.WebApi/Startup.cs

- Attempt to resolve URI creation within PlatformHub.
- Remove unused old Signalr Dependency
- WalletProvider tweak to handle nulls w/out NullRefException

Socket Fix w/ URI Creation

---

src/Opdex.Platform.Application.Abstractions/Models/VaultGovernances/VaultGovernanceDto.cs
src/Opdex.Platform.Application/Assemblers/VaultGovernanceDtoAssembler.cs
src/Opdex.Platform.WebApi/Mappers/PlatformWebApiMapperProfile.cs
src/Opdex.Platform.WebApi/Models/Responses/VaultGovernances/VaultGovernanceResponseModel.cs
src/Opdex.Platform.WebApi/Opdex.Platform.WebApi.csproj
test/Opdex.Platform.Application.Tests/Assemblers/VaultGovernanceDtoAssemblerTests.cs

Adds a `TokensLocked` property to the vault governance response

[PAPI-299] Return vault governance TokensLocked

---

src/Opdex.Platform.WebApi/OpenApi/SingleAllOfToRefDocumentProcessor.cs
src/Opdex.Platform.WebApi/Startup.cs

Enables ReadMe to parse and display paginated response models
See https://docs.opdex.com/reference/transactions_gettransactions for results

[PAPI-301] DocumentProcessor to transform allOf to ref

---

test/k6/README.md
test/k6/market-page-rpm.js

* Guidelines for writing load tests

[PAPI-171] Load testing guidelines with first test

---

src/Opdex.Platform.Application/EntryHandlers/Tokens/Quotes/CreateSwapTransactionQuoteCommandHandler.cs
test/Opdex.Platform.Application.Tests/EntryHandlers/Tokens/Quotes/CreateSwapTransactionQuoteCommandHandlerTests.cs

Resolves slippage bug for quoted transaction

[PAPI-304] Send maximum CRS amount when SwapCrsForExactSrc

---

src/Opdex.Platform.WebApi/Controllers/MiningPoolsController.cs
src/Opdex.Platform.WebApi/Controllers/TokensController.cs
src/Opdex.Platform.WebApi/OpenApi/MiningPools/CollectMiningRewardsOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/MiningPools/GetMiningPoolOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/MiningPools/StartMiningOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/MiningPools/StopMiningOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/OpenApiParameterExtensions.cs
src/Opdex.Platform.WebApi/OpenApi/Tokens/ApproveAllowanceOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/Tokens/DistributeOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/Tokens/GetTokenHistoryOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/Tokens/GetTokenOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/Transactions/GetTransactionOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/GetCertificatesOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/GetPledgeOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/GetProposalOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/GetVaultOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/GetVaultProposalPledgesOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/GetVaultProposalVotesOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/GetVaultProposalsOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/GetVoteOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuoteCompleteProposalOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuotePledgeOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuoteProposeCreateCertificateOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuoteProposeMinimumPledgeOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuoteProposeMinimumVoteOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuoteProposeRevokeCertificateOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuoteRedeemCertificateOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuoteVoteOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuoteWithdrawPledgeOperationProcessor.cs
src/Opdex.Platform.WebApi/OpenApi/VaultsGovernances/QuoteWithdrawVoteOperationProcessor.cs

* Defines schema mining pool params in the OAS doc
* Tweak to token params so that endpoint responds with 400 when token cannot be CRS

[PAPI-308] Mining pool route parameters

---

azure-pipelines.yml
test/k6/ci/status/get-status.js
test/k6/get-liquidity-pools.js
test/k6/market-page-rpm.js

* Stress test for `GET /liquidity-pools`, used for evaluating performance degradation
* Added first CD performance test, runs after deployment to testnet

[PAPI-171] Further load testing and performance tests

---

src/Opdex.Platform.Application/EntryHandlers/VaultGovernances/CreateVaultProposalCreateCertificateQuoteCommandHandler.cs
src/Opdex.Platform.Application/EntryHandlers/VaultGovernances/CreateVaultProposalMinimumPledgeQuoteCommandHandler.cs
src/Opdex.Platform.Application/EntryHandlers/VaultGovernances/CreateVaultProposalMinimumVoteQuoteCommandHandler.cs
src/Opdex.Platform.Application/EntryHandlers/VaultGovernances/CreateVaultProposalRevokeCertificateQuoteCommandHandler.cs
src/Opdex.Platform.Domain/Models/VaultGovernances/VaultProposalSummary.cs
src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/Extensions/TransactionErrors.cs
test/Opdex.Platform.Infrastructure.Tests/CirrusFullNodeApiTests/Handlers/VaultGovernances/CallCirrusGetVaultProposalSummaryByProposalIdQueryHandlerTests.cs

Added proposal deposit to transaction quotes and new errors

Proposal Deposit

---

src/Opdex.Platform.Application.Abstractions/Queries/Tokens/RetrieveTokenSummaryByTokenIdQuery.cs
src/Opdex.Platform.Application/Assemblers/TokenDtoAssembler.cs
src/Opdex.Platform.Application/Handlers/Tokens/RetrieveTokenSummaryByTokenIdQueryHandler.cs
src/Opdex.Platform.Application/PlatformApplicationServiceCollectionExtensions.cs
src/Opdex.Platform.Infrastructure.Abstractions/Data/Queries/Tokens/Summaries/SelectTokenSummaryByTokenIdQuery.cs
src/Opdex.Platform.Infrastructure/Data/Handlers/Tokens/Summaries/SelectTokenSummaryByTokenIdQueryHandler.cs
src/Opdex.Platform.Infrastructure/PlatformInfrastructureServiceCollectionExtensions.cs
test/Opdex.Platform.Application.Tests/Assemblers/TokenDtoAssemblerTests.cs

Ready - tried it out across multiple markets

[PAPI-320] Retrieve token summary for regular tokens

---

src/Opdex.Platform.Application.Abstractions/Models/LiquidityPools/LiquidityPoolDto.cs
src/Opdex.Platform.Application.Abstractions/Models/LiquidityPools/LiquidityPoolSummaryDto.cs
src/Opdex.Platform.Application/Assemblers/LiquidityPoolDtoAssembler.cs
src/Opdex.Platform.WebApi/Mappers/PlatformWebApiMapperProfile.cs
src/Opdex.Platform.WebApi/Models/Responses/LiquidityPools/LiquidityPoolResponseModel.cs
src/Opdex.Platform.WebApi/Models/Responses/LiquidityPools/Summary/LiquidityPoolSummaryResponseModel.cs

- Removed `MiningPool` from `LiquidityPool.Summary`
- Placed `MiningPool` in top level `LiquidityPoolResponseModel`

Liquidity Pool Response Model

---

src/Opdex.Platform.Infrastructure.Abstractions/Clients/CirrusFullNodeApi/CirrusConfiguration.cs
src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/CirrusHttpClientBuilder.cs

Makes the `CirrusConfiguration.ApiPort` optional

Cirrus Port Configuration

---

src/Opdex.Platform.Infrastructure/Data/Handlers/Tokens/SelectTokensWithFilterQueryHandler.cs

Resolves backward paging. When paging backward, the outer select query was failing because of duplicate column names (from the summary table). To resolve, the subquery is altered so that names are not duplicated and every query now wraps the subquery to return the correct column names to be mapped.

[PAPI-332] Fix tokens backward paging

---

src/Opdex.Platform.Common/Configurations/AuthConfiguration.cs
src/Opdex.Platform.WebApi/Controllers/WalletsController.cs
src/Opdex.Platform.WebApi/Middleware/SslValidationMiddleware.cs
src/Opdex.Platform.WebApi/Opdex.Platform.WebApi.csproj
src/Opdex.Platform.WebApi/Startup.cs

Check request certificates against whitelist.
Temporarily returning Forbidden for requests not whitelisted.

[PAPI-335] SSL Validation Middleware

---

src/Opdex.Platform.Infrastructure/Clients/SignalR/PlatformHub.cs
src/Opdex.Platform.WebApi/Controllers/AuthController.cs
test/Opdex.Platform.Infrastructure.Tests/SignalRTests/PlatformHubTests.cs
test/Opdex.Platform.WebApi.Tests/Controllers/AuthControllerTests.cs

Encrypt and validate expiration along with connectionId in SSAS flows

[PAPI-316] Stratis Id Expiration

---

src/Opdex.Platform.WebApi/Startup.cs

Excludes exception logs from sampling. Followed instructions here: https://docs.microsoft.com/en-gb/azure/azure-monitor/app/sampling#adaptive-sampling

Exclude exceptions from sampling

---

docs/openapi.yml
src/Opdex.Platform.Infrastructure/Data/DbContext.cs
src/Opdex.Platform.WebApi/Caching/BlockBasedCacheControlFilter.cs
src/Opdex.Platform.WebApi/Caching/CacheControlOptions.cs
src/Opdex.Platform.WebApi/Caching/CacheType.cs
src/Opdex.Platform.WebApi/Caching/CacheUntilNextBlockAttribute.cs
src/Opdex.Platform.WebApi/Controllers/BlocksController.cs
src/Opdex.Platform.WebApi/Controllers/LiquidityPoolsController.cs
src/Opdex.Platform.WebApi/Controllers/MarketTokensController.cs
src/Opdex.Platform.WebApi/Controllers/MarketsController.cs
src/Opdex.Platform.WebApi/Controllers/MiningGovernancesController.cs
src/Opdex.Platform.WebApi/Controllers/MiningPoolsController.cs
src/Opdex.Platform.WebApi/Controllers/TokensController.cs
src/Opdex.Platform.WebApi/Controllers/TransactionsController.cs
src/Opdex.Platform.WebApi/Controllers/VaultsController.cs
src/Opdex.Platform.WebApi/Controllers/WalletsController.cs
src/Opdex.Platform.WebApi/Startup.cs

[PAPI-221] Cache-Control headers

---

src/Opdex.Platform.Domain/Models/Vaults/VaultProposalCertificate.cs
src/Opdex.Platform.Infrastructure.Abstractions/Data/Models/Vaults/VaultProposalCertificateEntity.cs
src/Opdex.Platform.Infrastructure/Data/Handlers/Vaults/ProposalCertificates/PersistVaultProposalCertificateCommandHandler.cs
src/Opdex.Platform.Infrastructure/Data/Handlers/Vaults/ProposalCertificates/SelectVaultProposalCertificateByProposalIdQueryHandler.cs
src/Opdex.Platform.Infrastructure/Data/Handlers/Vaults/ProposalCertificates/SelectVaultProposalCertificatesByCertificateIdQueryHandler.cs
src/Opdex.Platform.Infrastructure/PlatformInfrastructureMapperProfile.cs
test/Opdex.Platform.Domain.Tests/Models/Vaults/VaultProposalCertificateTests.cs

- Resolves a bug where `vault_proposal_certificate` records are attempting to insert to `vault` table incorrectly 😢 
Related to https://github.com/Opdex/opdex-v1-db/pull/34

[PAPI-359] Vault Proposal Certificate Fix

---

docs/openapi.yml
src/Opdex.Platform.WebApi/Controllers/TransactionsController.cs
src/Opdex.Platform.WebApi/Models/Requests/Transactions/TransactionBroadcastNotificationRequest.cs
src/Opdex.Platform.WebApi/Validation/Transactions/TransactionBroadcastNotificationValidator.cs
test/Opdex.Platform.WebApi.Tests/Validation/Transactions/TransactionBroadcastNotificationValidatorTests.cs

Renames the `PublicKey` request property to `WalletAddress` to match the spec.

[PAPI-363] Transaction Notification Request

---

src/Opdex.Platform.Infrastructure/Data/Handlers/Tokens/SelectTokensWithFilterQueryHandler.cs

Resolves bug where a query to retrieve a previous page of token results with an order by filter would fail

[PAPI-364] Fix token paging backwards results

---

docs/openapi.yml
src/Opdex.Platform.Common/Converters/DecimalConverter.cs
src/Opdex.Platform.WebApi/Mappers/PlatformWebApiMapperProfile.cs
src/Opdex.Platform.WebApi/Models/Responses/Tokens/TokenResponseModel.cs

[PAPI-379] OpenAPI make large numbers easier to handle

---

src/Opdex.Platform.WebApi/Auth/AdminOnlyHandler.cs
src/Opdex.Platform.WebApi/Startup.cs
src/Opdex.Platform.WebApi/appsettings.json

Adds feature flag that enables auth flow using tokens issued by the Opdex Auth API.

Feature flag for auth server

---

src/Opdex.Platform.Infrastructure/Clients/SignalR/PlatformHub.cs
src/Opdex.Platform.WebApi/Auth/AdminOnlyHandler.cs
src/Opdex.Platform.WebApi/Auth/AdminOnlyRequirement.cs
src/Opdex.Platform.WebApi/Auth/WalletAddressUserIdProvider.cs
src/Opdex.Platform.WebApi/Controllers/AuthController.cs
src/Opdex.Platform.WebApi/Models/ApplicationContext.cs
test/Opdex.Platform.WebApi.Tests/Auth/AdminOnlyHandlerTests.cs
test/Opdex.Platform.WebApi.Tests/Opdex.Platform.WebApi.Tests.csproj

Additional header key for management of the indexer

[PAPI-415] Indexer management key

---

src/Opdex.Platform.Application/EntryHandlers/Addresses/Mining/GetMiningPositionByPoolQueryHandler.cs
src/Opdex.Platform.Application/EntryHandlers/Addresses/Staking/GetStakingPositionByPoolQueryHandler.cs

Fixes bug where created and modified block were returning as 0.

Return created and modified block for positions

---

src/Opdex.Platform.Application/Handlers/Transactions/RetrieveCirrusTransactionByHashQueryHandler.cs

Logs transaction hash for retrieval failure

Transaction retrieval failure log improvement

---

docs/openapi.yml
src/Opdex.Platform.Application.Abstractions/Queries/Tokens/RetrieveTokenAttributesByTokenAddressQuery.cs
src/Opdex.Platform.Application.Abstractions/Queries/Tokens/RetrieveTokenAttributesByTokenIdQuery.cs
src/Opdex.Platform.Application/EntryHandlers/Addresses/Balances/CreateAddressBalanceCommandHandler.cs
src/Opdex.Platform.Application/EntryHandlers/Addresses/Balances/CreateRefreshAddressBalanceCommandHandler.cs
src/Opdex.Platform.Application/EntryHandlers/Addresses/Mining/CreateRefreshMiningPositionCommandHandler.cs
src/Opdex.Platform.Application/EntryHandlers/Addresses/Staking/CreateRefreshStakingPositionCommandHandler.cs
src/Opdex.Platform.Application/Handlers/Tokens/Attributes/RetrieveTokenAttributesByTokenAddressQueryHandler.cs
src/Opdex.Platform.Application/Handlers/Tokens/Attributes/RetrieveTokenAttributesByTokenIdQueryHandler.cs
src/Opdex.Platform.Application/PlatformApplicationServiceCollectionExtensions.cs
src/Opdex.Platform.Infrastructure.Abstractions/Data/Queries/Tokens/Attributes/SelectTokenAttributesByTokenAddressQuery.cs
src/Opdex.Platform.Infrastructure/Data/Handlers/Tokens/Attributes/SelectTokenAttributesByTokenAddressQueryHandler.cs
src/Opdex.Platform.Infrastructure/PlatformInfrastructureServiceCollectionExtensions.cs
test/Opdex.Platform.Application.Tests/Handlers/Addresses/Balances/CreateRefreshAddressBalanceCommandHandlerTests.cs

- When refreshing OLPT balances, refreshes the associated SRC balance for the user
- When refreshing staking positions, refreshes the ODX token balance for the user
- When refreshing mining positions, refreshes the OLPT balance for the user

[PAPI-425] Refresh related balances and positions

---

azure-pipelines.yml

Devnet is no longer used, remove it from releases

Remove Devnet From Pipelines

---

src/Opdex.Platform.Application/EntryHandlers/Tokens/CreateAddTokenCommandHandler.cs
src/Opdex.Platform.Infrastructure.Abstractions/Clients/CirrusFullNodeApi/Models/ContractCodeDto.cs
src/Opdex.Platform.Infrastructure.Abstractions/Clients/CirrusFullNodeApi/Queries/SmartContracts/CallCirrusGetContractCodeQuery.cs
src/Opdex.Platform.Infrastructure/Clients/CirrusFullNodeApi/Handlers/SmartContracts/CallCirrusGetContractCodeQueryHandler.cs
src/Opdex.Platform.Infrastructure/PlatformInfrastructureServiceCollectionExtensions.cs
test/Opdex.Platform.Application.Tests/EntryHandlers/Tokens/CreateAddTokenCommandHandlerTests.cs

Resolves issue w/ attempting to add tokens with addresses that are not smart contract addresses by retrieving contract code details of the address prior to fetching token details.

Verify Address is Contract
